# Generated by Django 6.0.1 on 2026-03-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(choices=[('IMPORTADO', 'Línea importada'), ('NACIONAL', 'Línea nacional'), ('UNICO', 'Talles únicos')], max_length=20)),
                ('foto_modelo', models.ImageField(upload_to='trajes/')),
                ('foto_colgado', models.ImageField(upload_to='trajes/')),
                ('tela', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talle_saco', models.CharField(max_length=50)),
                ('talle_pantalon', models.CharField(max_length=50)),
                ('traje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='catalogo.traje')),
            ],
        ),
    ]
