# Generated by Django 6.0.1 on 2026-03-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_accessorio_camisa_combo_zapato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_modelo', models.ImageField(upload_to='chalecos/')),
                ('foto_colgado', models.ImageField(upload_to='chalecos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Cinturon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_1', models.ImageField(upload_to='cinturones/')),
                ('foto_2', models.ImageField(upload_to='cinturones/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Corbata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_1', models.ImageField(upload_to='corbatas/')),
                ('foto_2', models.ImageField(upload_to='corbatas/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TalleColorCamisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TalleColorChaleco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
                ('chaleco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='catalogo.chaleco')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TalleColorZapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talle', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='TalleColor',
            new_name='TalleColorTraje',
        ),
        migrations.DeleteModel(
            name='Accessorio',
        ),
        migrations.AlterModelOptions(
            name='camisa',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='tallecolortraje',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='traje',
            options={'ordering': ['linea', '-creado']},
        ),
        migrations.AlterModelOptions(
            name='zapato',
            options={'ordering': ['-creado']},
        ),
        migrations.RenameField(
            model_name='camisa',
            old_name='foto',
            new_name='foto_colgado',
        ),
        migrations.RenameField(
            model_name='zapato',
            old_name='foto',
            new_name='foto_colgado',
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='color',
        ),
        migrations.RemoveField(
            model_name='camisa',
            name='talle',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='beneficio',
        ),
        migrations.RemoveField(
            model_name='zapato',
            name='color',
        ),
        migrations.RemoveField(
            model_name='zapato',
            name='talle',
        ),
        migrations.AddField(
            model_name='camisa',
            name='foto_modelo',
            field=models.ImageField(default=0, upload_to='camisas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='foto',
            field=models.ImageField(default=0, upload_to='combos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='precio_unico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapato',
            name='foto_modelo',
            field=models.ImageField(default=0, upload_to='zapatos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combo',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tallecolorcamisa',
            name='camisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='catalogo.camisa'),
        ),
        migrations.AddField(
            model_name='tallecolorzapato',
            name='zapato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='catalogo.zapato'),
        ),
    ]
