# Generated by Django 6.0.1 on 2026-04-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_chaleco_cinturon_corbata_tallecolorcamisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='precio_ninos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
