# Generated by Django 6.0.1 on 2026-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_combo_precio_ninos'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisa',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chaleco',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cinturon',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='corbata',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='traje',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zapato',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='traje',
            name='linea',
            field=models.CharField(choices=[('IMPORTADO', 'Linea importada'), ('NACIONAL', 'Linea nacional'), ('UNICO', 'Talles unicos')], max_length=20),
        ),
    ]
