# Generated by Django 6.0.1 on 2026-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_url', models.URLField(default='https://wa.me/5492213540416', help_text='Enlace completo de WhatsApp que se muestra en la web publica.')),
                ('instagram_url', models.URLField(blank=True, default='', help_text='Enlace completo del Instagram oficial.')),
                ('direccion_post_reserva', models.CharField(blank=True, default='', help_text='Direccion exacta que se muestra despues de confirmar la visita.', max_length=255)),
                ('mensaje_confirmacion', models.TextField(default='Tu visita quedo confirmada. Te esperamos en el horario elegido y si necesitas reprogramar, escribinos por WhatsApp.', help_text='Mensaje principal que se muestra al confirmar una visita.')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del sitio',
                'verbose_name_plural': 'Configuracion del sitio',
            },
        ),
    ]
