# Generated by Django 6.0.1 on 2026-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/abito.gonnet/', help_text='Enlace completo del Instagram oficial.'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp_url',
            field=models.URLField(default='https://wa.me/message/IXNVRCQIC6YFF1', help_text='Enlace completo de WhatsApp que se muestra en la web publica.'),
        ),
    ]
