# Generated by Django 6.0.1 on 2026-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('fecha_evento', models.DateField()),
                ('fecha_visita', models.DateField()),
                ('hora_visita', models.TimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
