# Generated by Django 6.0.1 on 2026-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['fecha', 'hora_inicio', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_visita', '-hora_visita', '-creado']},
        ),
        migrations.AddField(
            model_name='visita',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada'), ('NO_ASISTIO', 'No asistio')], default='CONFIRMADA', max_length=20),
        ),
        migrations.AddField(
            model_name='visita',
            name='observaciones_internas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visita',
            name='origen',
            field=models.CharField(choices=[('WEB', 'Web'), ('MANUAL', 'Manual')], default='WEB', max_length=20),
        ),
    ]
