# Generated by Django 6.0.1 on 2026-04-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_camisa_descripcion_chaleco_descripcion_and_more'),
        ('visitas', '0002_bloqueoagenda_alter_visita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='vio_prendas_catalogo',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vio prendas en el catalogo'),
        ),
        migrations.CreateModel(
            name='PreferenciaAmboVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('linea', models.CharField(blank=True, default='', max_length=20)),
                ('tela', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('talle_saco', models.CharField(max_length=50)),
                ('talle_pantalon', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('traje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencias_visita', to='catalogo.traje')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_ambos', to='visitas.visita')),
            ],
            options={
                'verbose_name': 'Preferencia de ambo',
                'verbose_name_plural': 'Preferencias de ambos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
